version: 2
jobs:
  build:
    docker:
      - image: silex/emacs:25.2
    working_directory: ~/winnow.el
    steps:
      - checkout
      - run: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - run: PATH="/root/.cask/bin:$PATH" make
